### ISSUE TITLE
RPi3?

### ISSUE THREAD

**Issue by simonredding** [ttn-liv/rpi-gateways#1]
Hi Patrick,

Good to meet you earlier this week. Thanks for showing me your TTN basestations...
Any reason why a Raspberry Pi 3 can't be used for your standard build?
It has the same form factor. Wondering if it's the power envelope or something.

Cheers
Simon

**Comment by DefProc** [comment]
There have been some reports in the TTN forums that the WiFi can cause some unexpected reboots of the LoRaWAN condenser (especially when using jumper wire connections), but the main reason for this build is that ethernet and power come in via a single cable (and the box is metal). 

If the ethernet connection goes back somewhere close to power, then wired connection provides a more reliable connection for little extra effort.
